### ISSUE TITLE
AOC 2023 Day 13 results seem incorrect

### ISSUE THREAD

**Issue by GunnarBernsteinHH** [ChristopherBiscardi/advent-of-code#24]
I have been following your YouTube videos and learned a lot. Many thanks for that!

For day 13 I get totally different results. Mine seem correct, since I received the gold stars.

For part 1 I get 200 running your code, but 34772 on mine.
For part 2 I get 134900 running your code, but 35554 on mine.

Maybe you can check if a mistake sneaked its way into the code base.

**Comment by ChristopherBiscardi** [comment]
glad you're enjoying them!

For testing the implementation it'll be hard for me to do that since the author of aoc has expressed that they don't want people sharing inputs (I won't be including them moving forward in this repo either). That makes it effectively impossible for me to figure out if a given solution is a proper general solution or one that just happens to work on a given input (which happens all the time in aoc. Some people get problem input that can be shortcut and others get the "full difficulty" for a given day).

Its entirely possible there's a mistake, but unfortunately I won't be able to test against other input to find it

**Comment by GunnarBernsteinHH** [comment]
There was a misunderstanding. I ran your input files, not mine. Basically you just need to compare the number you entered in the AOC contest and compare it with what your code now returns.
